import React, { useState } from 'react';
import Head from 'next/head'
import { useRouter } from 'next/router';
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const router = useRouter();
  const [searchTerms, setSearchTerms] = useState("Job Search");

  const performSearch = async () => {
    const url = `/search/q=${encodeURIComponent(searchTerms)}`;
    console.log(`pushing ${url}`)
    router.push(url);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <div className="container mx-auto px-6 py-16 pt-28 text-center">
          <div className="mx-auto max-w-lg">
            <h1 className="text-3xl font-bold text-gray-800 dark:text-white md:text-4xl">Create Resume Using ChatGPT</h1>

            <p className="mt-6 text-gray-500 dark:text-gray-300">Search for jobs and get AI generated resumes</p>

            <div
                className="mx-auto mt-6 w-full max-w-sm rounded-md border bg-transparent focus-within:border-blue-400 focus-within:ring focus-within:ring-blue-300 focus-within:ring-opacity-40 dark:border-gray-700 dark:focus-within:border-blue-300">
              <form className="flex flex-col md:flex-row">
                <input type="text"
                       value={searchTerms}
                       className="m-1 h-10 flex-1 appearance-none border-none bg-transparent px-4 py-2 text-gray-700 placeholder-gray-400 focus:placeholder-transparent focus:outline-none focus:ring-0 dark:text-gray-200"
                       onChange={(e) => setSearchTerms(e.target.value )}
                />

                <button type="button"
                        className="m-1 h-10 transform rounded-md bg-blue-500 px-4 py-2 text-white transition-colors duration-300 hover:bg-blue-400 focus:bg-blue-400 focus:outline-none"
                        onClick={() => performSearch()}
                >Search
                </button>
              </form>

            </div>

          </div>
          <div className="mx-auto max-w-lg py-5">
            <button
                className="w-full transform rounded-lg bg-gray-800 px-6 py-2.5 text-sm font-medium tracking-wider text-white transition-colors duration-300 hover:bg-gray-700 focus:outline-none focus:ring focus:ring-gray-300 focus:ring-opacity-80 md:mx-4 md:w-auto"
                onClick={() => {
                  setSearchTerms(searchTerms + " work from home");
                }}
            >Remote
            </button>
            <button
                className="w-full transform rounded-lg bg-gray-800 px-6 py-2.5 text-sm font-medium tracking-wider text-white transition-colors duration-300 hover:bg-gray-700 focus:outline-none focus:ring focus:ring-gray-300 focus:ring-opacity-80 md:mx-4 md:w-auto"
                onClick={() => {
                  setSearchTerms(searchTerms + " hybrid");
                }}
            >Hybrid
            </button>
          </div>
        </div>
      </main>
    </>
  )
}
